### ISSUE TITLE
Problems with LogCenter path

### ISSUE THREAD

**Issue by L1brTy** [biocoder-frodo/FRITZBox-SynologyLogCenterDaemon#5]
Hi, 

I have problems testing the script.

I copied everything to 
`/var/services/homes/admin`

I call the command:

`sudo php fritzbox-syslog-daemon.php -u iobroker -l=/var/services/homes/l1berty/Drive/syslog`

with the following result:

`pid =15116`
`array(1) {`
`  ["u"]=>`
`  bool(false)`
`}`
`LogCenter path must be specified`

content of the syslog folder:
`@ds18:~/Drive/syslog$ ll`
`total 32048`
`drwxrwxrwx+ 2 l1berty users     4096 Oct 10 13:55 .`
`drwxrwxrwx+ 5 l1berty users     4096 Dec 19  2018 ..`
`-rwxrwxrwx+ 1 system  log   32804864 Oct 10 13:37 SYNOSYSLOGDB__ARCH.DB`

any hints for me ? 

Best regards

**Comment by biocoder-frodo** [comment]
Please note the difference in 

```
php -v
PHP 5.6.11 (cli) (built: Mar 18 2021 13:39:25)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```
and
```
php72 -v
PHP 7.2.29 (cli) (built: Jun  5 2020 14:21:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

Also, the values for the parameters should be prepended with the = character, like so
` php72 fritzbox-syslog-daemon.php -d -u=yolo -l=/`

**Comment by L1brTy** [comment]
thx for the answer. 

I had to install php72 manual.

best regards
