### ISSUE TITLE
Fritzbox Login failed

### ISSUE THREAD

**Issue by L1brTy** [biocoder-frodo/FRITZBox-SynologyLogCenterDaemon#6]
Hi, 
how should the content of the password file look like ? 

I tried plain text and md5 hashed.

cat stats.pwdfile
12testpw

Fritzbox shows wrong password in the events.

output is : 
`pid =484`
`array(5) {`
 ` ["l"]=>`
 ` string(34) "/volume1/homes/admin/fritzbox/logs"`
 ` ["q"]=>`
 ` bool(false)`
 ` ["a"]=>`
 ` bool(false)`
 ` ["j"]=>`
 ` bool(false)`
 ` ["t"]=>`
 ` string(4) "http"`
`}`
`Please come back in 128 seconds..`
`Login failed`
 `closing CURL session  complete`

Best regards

**Comment by biocoder-frodo** [comment]
It's in plaintext. Which user do you want the script to login with?

**Comment by L1brTy** [comment]
At the end I created the user stats with password 12testpw.

I called the script with `sudo php72 fritzbox-syslog-daemon.php   -l='/volume1/homes/admin/fritzbox/logs' -q -a -j -t=http`

**Comment by biocoder-frodo** [comment]
Your stats.pwdfile should contain just the password, so it should be 1 line without the special characters for Carriage Return and Line Feed. If your password is 36 characters, the file size must be 36 bytes.
Screenshot on Windows with Notepad++ to show an incorrect example:
![image](https://user-images.githubusercontent.com/3184378/195435796-080343af-3d50-4def-9f0d-e8c72c47991f.png)

The function to show all characters is the left highlighted button in the app's toolbar.

**Comment by biocoder-frodo** [comment]
I think you sorted this one out yourself :)
